// [""ĐIỀU KHIẾN NGƯỜI KHÁC CHÊ CƯỜI KHÔNG PHẢI LÀ 
// ƯỚC MƠ CỦA BẠN MÀ LÀ THỰC LỰC CỦA BẠN

// NẾU CHƯA TỪNG ĐIÊN CƯỜNG VÌ ƯỚC MƠ CỦA MÌNH BẠN 
// ĐÃ PHỤ THANH XUÂN MẤT RỒI

// CHỈ CẦN NỖI LỰC, BẠN SẼ HIỆN THỰC ĐƯỢC ƯỚC MƠ CỦA
// MÌNH TRỞ THÀNH ANH HÙNG CỦA CHÍNH MÌNH, KHÔNG ĐỄ
// NỖI GIÀY VÒ HỐI HẬN SUỐC CUỘC ĐỜI"",""dù bắt đầu ở vị trí nào thì luôn phải cải thiện bản thân- coding - outsource product -kĩ năng lead vẫn quan trọng hơn 
// Hmm, về quan điểm thì tôi nghĩ là có 1 vài thứ đáng bàn.

// Vấn đề về sản phẩm của cty outsource hay product, thì chúng ta nên xem xét nó ở góc độ học thuật 1 chút, tức là cái j đã làm nên sự khác biệt trong mindset khi làm outsource vs product? Có 2 yếu tố mà tôi nghĩ là nguyên nhân chính, đó là vòng đời của code, và số lượng người sử dụng. Và có lẽ đặc điểm là vòng đời ngắn và số lượng người sử dụng ít dẫn đến tư duy là ko quá coi trọng code quality so với time to market và không cần phải hiểu về end customer so với chiều ngược lại nên mới có những cuộc tranh cãi ở đây chăng? Bản thân tôi thấy đây chỉ là góc nhìn ở những hệ quy chiếu khác nhau, mà một người lead phải nắm rõ để điều chỉnh khi giải quyết trong từng project cụ thể vì bản thân trong cty product, bạn cũng sẽ phải làm những dự án ngắn hạn, và ngược lại. Đương nhiên mình nghĩ khi còn trẻ thì nên trải nghiệm ở nhiều môi trường khác nhau để thực sự hiểu và có cái nhìn khách quan hơn về vấn đề này.

// Vấn đề thứ 2 là chủ thớt có nói là ở outsource, thì dev bị đối xử rẻ mạt, và hoàn toàn có thể thay thế, thì mình cũng chia sẻ là đó là vấn đề ở bất cứ công ty nào, tức là khi bạn muốn scale 1 công ty lên thì bắt buộc bạn ko có single point of failure, tức là bất cứ nhân viên nào cũng có thể thay thế đc mà ko ảnh hưởng đến cả bộ máy. Trong nhiều cty, bạn sẽ thấy có policy bắt buộc nhân viên phải nghỉ 1 tháng khi đã làm đc X năm, để đảm bảo là team đó vẫn hoạt động bt mà ko quá phụ thuộc vào cá nhân cụ thể.

// Vậy cuối cùng, vấn đề đáng bàn ở đây là j? quan điểm riêng của mình, thì dù bắt đầu ở vị trí nào, cái khó nhất mà mỗi cá nhân phải giải quyết, để nâng cao giá trị bản thân, đó là bài toán con người, anh có làm x2, x3 người khác, thì giá trị của anh cũng thế x2, x3 và sẽ giảm dần theo tgian, nhưng nếu anh lead đc x10, x100 người, thì giá trị của bản thân cũng x10, x100 thôi. Vậy câu hỏi ở đây là, làm outsource có thể có điều kiện rèn luyện như vậy ko? mình xin để các bạn outsource trả lời vì mình chưa làm outsource bao h hề hề.

// Mình xin giới thiệu quyển sách mình đang đọc của cty mình, ae có thể tham khảo Software Engineering at Google, để có góc nhìn đa chiều hơn, hy vọng sẽ có bản free cho ae trong tgian tới.
// Last edited: De"",""câu chuyện ngày tết, không nhất thiết phải gặng 
// hỏi ai một vấn đề gì đó khi mà người ta
// đã khônh muốn nói

// lắng nghe và quan sát sẽ thấy nhiều chi tiết thú vị""]

// NẾU CHƯA TỪNG ĐIÊN CƯỜNG VÌ ƯỚC MƠ CỦA MÌNH BẠN \
// ĐÃ PHỤ THANH XUÂN MẤT RỒI
a = "ĐIỀU KHIẾN NGƯỜI KHÁC CHÊ CƯỜI KHÔNG PHẢI LÀ ƯỚC MƠ CỦA BẠN MÀ LÀ THỰC LỰC CỦA BẠN NẾU CHƯA TỪNG ĐIÊN CUỒNG VÌ ƯỚC MƠ CỦA MÌNH BẠN ĐÃ PHỤ THANH XUÂN MẤT RỒI CHỈ CẦN NỖI LỰC, BẠN SẼ HIỆN THỰC ĐƯỢC ƯỚC MƠ CỦA MÌNH TRỞ THÀNH ANH HÙNG CỦA CHÍNH MÌNH, KHÔNG ĐỄ NỖI GIÀY VÒ HỐI HẬN SUỐC CUỘC ĐỜI";
b = "câu chuyện ngày tết, không nhất thiết phải gặng hỏi ai một vấn đề gì đó khi mà người ta đã khônh muốn nói lắng nghe và quan sát sẽ thấy nhiều chi tiết thú vị";
du_bat_dau_o_vi_tri_nao_cung_can_co_gang = "dù bắt đầu ở vị trí nào thì luôn phải cải thiện bản thân- coding - outsource product -kĩ năng lead vẫn quan trọng hơn Hmm, về quan điểm thì tôi nghĩ là có 1 vài thứ đáng bàn. Vấn đề về sản phẩm của cty outsource hay product, thì chúng ta nên xem xét nó ở góc độ học thuật 1 chút, tức là cái j đã làm nên sự khác biệt trong mindset khi làm outsource vs product? Có 2 yếu tố mà tôi nghĩ là nguyên nhân chính, đó là vòng đời của code, và số lượng người sử dụng. Và có lẽ đặc điểm là vòng đời ngắn và số lượng người sử dụng ít dẫn đến tư duy là ko quá coi trọng code quality so với time to market và không cần phải hiểu về end customer so với chiều ngược lại nên mới có những cuộc tranh cãi ở đây chăng? Bản thân tôi thấy đây chỉ là góc nhìn ở những hệ quy chiếu khác nhau, mà một người lead phải nắm rõ để điều chỉnh khi giải quyết trong từng project cụ thể vì bản thân trong cty product, bạn cũng sẽ phải làm những dự án ngắn hạn, và ngược lại. Đương nhiên mình nghĩ khi còn trẻ thì nên trải nghiệm ở nhiều môi trường khác nhau để thực sự hiểu và có cái nhìn khách quan hơn về vấn đề này. Vấn đề thứ 2 là chủ thớt có nói là ở outsource, thì dev bị đối xử rẻ mạt, và hoàn toàn có thể thay thế, thì mình cũng chia sẻ là đó là vấn đề ở bất cứ công ty nào, tức là khi bạn muốn scale 1 công ty lên thì bắt buộc bạn ko có single point of failure, tức là bất cứ nhân viên nào cũng có thể thay thế đc mà ko ảnh hưởng đến cả bộ máy. Trong nhiều cty, bạn sẽ thấy có policy bắt buộc nhân viên phải nghỉ 1 tháng khi đã làm đc X năm, để đảm bảo là team đó vẫn hoạt động bt mà ko quá phụ thuộc vào cá nhân cụ thể. Vậy cuối cùng, vấn đề đáng bàn ở đây là j? quan điểm riêng của mình, thì dù bắt đầu ở vị trí nào, cái khó nhất mà mỗi cá nhân phải giải quyết, để nâng cao giá trị bản thân, đó là bài toán con người, anh có làm x2, x3 người khác, thì giá trị của anh cũng thế x2, x3 và sẽ giảm dần theo tgian, nhưng nếu anh lead đc x10, x100 người, thì giá trị của bản thân cũng x10, x100 thôi. Vậy câu hỏi ở đây là, làm outsource có thể có điều kiện rèn luyện như vậy ko? mình xin để các bạn outsource trả lời vì mình chưa làm outsource bao h hề hề. Mình xin giới thiệu quyển sách mình đang đọc của cty mình, ae có thể tham khảo Software Engineering at Google, để có góc nhìn đa chiều hơn, hy vọng sẽ có bản free cho ae trong tgian tới. Last edited: De";
backup_data = "do sợ mất mát thông tin lên mình sẽ vứt hết toàn bộ file để drive"
viet_cho_20 = "Viết cho 20 lần 2 hôm nay là một ngày gió lạnh đối với người khác còn đối với tôi, thằng con trai 20 tuổi vẫn hừng hực khí thế chạy bộ như trâu húc mả, đấy là đối với tụi bạn tôi, không nên so sánh vì mấy ô đó có chạy mấy đâu mình chạy suốt lại một minh chứng cho sự rèn luyện ắt thành, tôi sẽ cố gắng tập luyện nhiều hơn họ vì nếu cũng chỉ tập bằng họ thì tôi lại bị kéo xuống nấc thang dưới Cũng như vậy việc học tập tôi cần cố gắng hơn Truyện ăn và mindset khi học Khi mà tôi ăn đói và không khoa học dẫn đến việc đau bụng dữ dội ảnh hưởng đến học tập Ngoài việc mục tiêu hướng đến sự tiết kiệm thì còn 1 lý do nữa đó là stress và lười Cũng giống như việc đi ngủ sớm thay vì thức khuya cố gắng học tập Và sự tập trung trên lớp và sự cố gắng lúc về nhà => ĂN KHÔNG NHIỀU QUÁ KHÔNG VÔ TỘI VẠ NHƯNG ĐÚNG ĐỦ BỮA, CÓ CHẤT, MÌNH PHẢI ĂN CHỨ KHÔNG ĐƯỢC NHỊN HOẶC ĂN MÌ QUÁ NHIỀU, THAY VÀO ĐÓ ĂN RAU VÀ ĂN TRỨNG CŨNG NHƯ KHÔNG TƯƠNG ỚT HOẶC ĐỒ QUÁ CAY VIỆC TẮM VÀ BỐC PHÉT BIẾT BẢN THÂN CHẲNG CÓ GÌ THÌ NGẬM MÕM LẠI Tôi làm những điều vô ích như giải thích, nói lên quan điểm cá nhân phê phán người khác, chêu trọc người trong công viên tiêu chuẩn của tôi bị đánh thấp tôi tiêu hết 25,30,10 -> 65 = 2 cái tai nghe tôi học tập sẽ là vô ích nếu tôi không ôn lại, thực sự rất nhiều thứ cần phải học";
tro_mot_minh = "Trọ 1 mình 19 tuổi là đã có thể tự lo cho bản thân được r, ở 1 mình thì bạn chỉ có mỗi việc chú tâm lo cho bản thân chứ còn lo gì nữa. Thứ nhất, ở một mình nhưng vẫn nên chú ý nấu nướng, ngủ nghỉ, tắm rửa vẫn phải giữ sạch sẽ, phải sáng, môi trường xung quanh sạch sẽ, tươm tất thì nó làm cho tinh thần mình rất thoải mái, làm việc gì cũng tràn năng lượng ==> dành cố định 1 ngày trong tuần để tổng vệ sinh. Thứ hai, bạn biết tính toán chi phí cho từng thứ nhỏ mà khi ở với gia đình bạn không phải lo nghĩ như tiền nước, điện hàng tháng, hoá đơn cho 1 ngày ăn. Thứ ba, ở một mình thì hạn chế mời bạn bè qua nhà ăn uống nhậu nhẹt==> tạo 1 thói quen xấu, mà mỗi lần nhậu nhẹt vậy thì phòng ốc đều rối tung rối mù do cuộc vui để lại==> chỗ mình ở mà bừa bộn thì mình cũng ức chế chứ. Thứ tư, không có ai nhắc nhở mình từng ly từng tý cho cái việc sáng ngủ dậy tự gắp chăn mền, tối thì 23h tự bắt đầu đi ngủ, thì mình phải tự chủ, tạo cho bản thân thói quen lành mạnh. Thứ năm, tạo cho mình một sở thích, thí dụ như chơi nhạc cụ, học ngôn ngữ, chơi 1 môn thể thao, đi tập tạ,... mục đích là để giết chết cái khoảng thời gian vô bổ bạn dành cho lang thang internet, chơi game, quay tay, xem porn,... Kết luận, tự lập là là tự lập từ những thứ nho nhỏ rồi từ từ đi lên những cái lớn, không ai có thể vừa mới thoát ly khỏi cha khỏi mẹ mà có thể tự làm ra tiền, tự lo cho bản thân, tự đủ lông đủ cánh mà bay được bạn. Những thay đổi nhỏ ngày hôm nay là nền tảng cho những thay đổi lớn của ngày hôm sau, quá trình nó cứ nối tiếp, nối tiếp nhau tuần tự như vậy. Chúc bạn thành công";
var qoutes = [a,b,du_bat_dau_o_vi_tri_nao_cung_can_co_gang,backup_data,viet_cho_20,tro_mot_minh]

function newQuote()
{
	var randomNum = Math.floor(Math.random()*(qoutes.length));
	document.getElementById('quoteDisplay').innerHTML = qoutes[randomNum];
}

// một là auto random
// hai là trích suất nội dung từ file txt, đưa các nội dung thành 1 list